#!/usr/bin/env bash
# transfers a file from our client to a server
# argv1 - The path to the file to be transferred
# argv2 - The IP of the server we want to transfer the file to
# argv3 - The username scp connects with
# argv4 - The path to the SSH private key that scp uses

if [ $# != 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
