#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chmod -R 755 /var/www

echo "Hello world!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
server_config=\
"server{
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$Web-01;
	location / {
		try_files \$uri \$uri/ =404;
	}
	
	if (\$request_filename ~ redirect_me){
                rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"


echo -e "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx start
