#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello world!" > /var/www/html/index.ngingx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
server_config=\
"server{
	listen 80 default_server;
	listen [::]:80 default_server;
		root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
	
	if (\$request_filename ~ redirect_me){
                rewrite ^ https://youtube.com/watc?v=QH2-TGUlwu4 permanent;

}"


echo -e "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx start
