#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page
" > /var/www/html/404.html
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "46i error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i "46i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
/etc/init.d/nginx restart
