#!/usr/bin/env bash
sudo apt-get update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get update
sudo apt-get install haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "defaults
	log	global
	mode	http
	option	httplog

frontend web-server
	bind *:80
	default_backend app-servers
	
backend app-servers
	balance	roundrobin
	server 57647-web-01 54.197.73.242:80 check
	server 57647-web-02 54.208.60.185:80 check" >> /etc/haproxy/haproxy.cfg

#Enable haproxy to be managed via init script
systemctl enable haproxy

#start haproxy
systemctl start haproxy
