#!/usr/bin/env bash
#Creating a script that uses a nested loop
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
